package hooks

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// LegacyKept is where migration moves the settings file; the generated hooks source it.
const LegacyKept = "service-backup-settings.legacy.sh"

// rename is os.Rename, replaced in tests to make the last step fail.
var rename = os.Rename

// Migration is what migrating one service directory did.
type Migration struct {
	Dir      string
	Wrote    []string // files created
	Warnings []string
}

// The wrappers stand in for the two Archiver functions existing hooks call, which ran in
// Archiver's own shell before. Their output reaches the log either way.
const helpers = `log_message() { if [ "$1" = WARNING ] || [ "$1" = ERROR ]; then echo "[$1] $2" >&2; else echo "$2"; fi; }
log_output() { local l; while IFS= read -r l || [ -n "$l" ]; do case "${1:-INFO}" in ERROR|WARNING) echo "[$1] $l" ;; *) echo "$l" ;; esac; done; }
handle_error() { echo "[ERROR] $1" >&2; return "${2:-1}"; }
`

const wrapperHead = `#!/bin/bash
# Generated by 'archiver migrate hooks' from service-backup-settings.sh, which is kept as
# service-backup-settings.legacy.sh. Replace this file with a plain script whenever you like.
` + helpers + `SERVICE="${ARCHIVER_SERVICE}"
SERVICE_DIR="${ARCHIVER_SERVICE_DIR}"
DUPLICACY_SNAPSHOT_ID="${ARCHIVER_SNAPSHOT_ID}"
DUPLICACY_REPO_DIR="${ARCHIVER_SERVICE_DIR}/.duplicacy"
cd "${ARCHIVER_SERVICE_DIR:-$(dirname "$0")}" || exit 1
# shellcheck source=/dev/null
source ./` + LegacyKept + ` || { echo "[ERROR] ` + LegacyKept + ` failed to load (exit $?)" >&2; exit 1; }
`

// Migrate converts dir's service-backup-settings.sh into executable hooks and a filters
// file. It is a no-op for a directory with no settings file. It uses bash to read the
// file's filter list and functions, which runs the file's top level once, as every backup
// already did.
func Migrate(dir, hostname string) (*Migration, error) {
	if abs, err := filepath.Abs(dir); err == nil {
		dir = abs
	}
	legacy := filepath.Join(dir, Legacy)
	if _, err := os.Stat(legacy); os.IsNotExist(err) {
		return nil, nil
	}
	// Migration sources the file as root, so it is held to the rule for hooks (ADR 45).
	if err := Safe(legacy); err != nil {
		return nil, err
	}
	for _, name := range []string{PreBackup, PostBackup, Filters, LegacyKept} {
		if _, err := os.Lstat(filepath.Join(dir, name)); err == nil {
			return nil, fmt.Errorf("%s: %s already exists; move it aside and run the migration again", dir, name)
		}
	}
	src, err := os.ReadFile(legacy)
	if err != nil {
		return nil, err
	}
	probe := exec.Command("bash", "-c", helpers+`
source ./`+Legacy+` >/dev/null || exit 3
declare -F service_specific_pre_backup_function >/dev/null && echo pre
declare -F service_specific_post_backup_function >/dev/null && echo post
if declare -p DUPLICACY_FILTERS_PATTERNS >/dev/null 2>&1; then
  echo filters
  printf '%s\0' "${DUPLICACY_FILTERS_PATTERNS[@]}" >&3
fi
`)
	probe.Dir = dir
	// The variables main.sh had set before it sourced the file, which a filter may use.
	service := filepath.Base(dir)
	probe.Env = append(withoutSecrets(os.Environ()),
		"SERVICE="+service,
		"SERVICE_DIR="+dir,
		"DUPLICACY_SNAPSHOT_ID="+hostname+"-"+service,
		"DUPLICACY_REPO_DIR="+filepath.Join(dir, ".duplicacy"),
	)
	var funcs, filters, stderr bytes.Buffer
	probe.Stdout = &funcs
	probe.Stderr = &stderr
	r, w, err := os.Pipe()
	if err != nil {
		return nil, err
	}
	probe.ExtraFiles = []*os.File{w}
	done := make(chan struct{})
	go func() { _, _ = filters.ReadFrom(r); close(done) }()
	err = probe.Run()
	w.Close()
	<-done
	r.Close()
	if err != nil {
		return nil, fmt.Errorf("%s: %s could not be read by bash (%v: %s); fix it, then migrate", dir, Legacy, err, strings.TrimSpace(stderr.String()))
	}
	have := map[string]bool{}
	for _, f := range strings.Fields(funcs.String()) {
		have[f] = true
	}

	m := &Migration{Dir: dir}
	// A half-done migration would switch the deployment to the Go pipeline, which refuses
	// the unmigrated service, and block a retry: undo whatever this attempt wrote.
	migrated := false
	defer func() {
		if !migrated {
			for _, name := range m.Wrote {
				os.Remove(filepath.Join(dir, name))
			}
		}
	}()
	write := func(name, content string, mode os.FileMode) error {
		// Recorded first, so a write that fails partway is rolled back too.
		m.Wrote = append(m.Wrote, name)
		return os.WriteFile(filepath.Join(dir, name), []byte(content), mode)
	}
	if have["pre"] {
		if err := write(PreBackup, wrapperHead+"service_specific_pre_backup_function\n", 0o755); err != nil {
			return nil, err
		}
	}
	if have["post"] {
		if err := write(PostBackup, wrapperHead+"service_specific_post_backup_function\n", 0o755); err != nil {
			return nil, err
		}
	}
	if have["filters"] {
		var lines []string
		for _, p := range strings.Split(strings.TrimSuffix(filters.String(), "\x00"), "\x00") {
			lines = append(lines, renameInFilter(p, m.created())...)
		}
		if err := write(Filters, strings.Join(lines, "\n")+"\n", 0o644); err != nil {
			return nil, err
		}
	}
	if err := rename(legacy, filepath.Join(dir, LegacyKept)); err != nil {
		return nil, fmt.Errorf("%s: moving %s aside: %w", dir, Legacy, err)
	}
	migrated = true
	for _, line := range strings.Split(filters.String(), "\x00") {
		if strings.Contains(line, strings.TrimSuffix(Legacy, ".sh")) && !strings.HasSuffix(line, Legacy) {
			m.Warnings = append(m.Warnings, fmt.Sprintf("%s: the filter %q names the settings file in a form this migration does not rewrite. Make sure the filters file still selects %s, %s, %s and %s.", dir, line, PreBackup, PostBackup, Filters, LegacyKept))
		}
	}
	if have["filters"] && shellVariable.MatchString(arrayText(string(src))) {
		m.Warnings = append(m.Warnings, fmt.Sprintf("%s: DUPLICACY_FILTERS_PATTERNS used variables; the filters file holds their values as of this migration. Check it.", dir))
	}
	if have["pre"] && have["post"] {
		for _, v := range sharedVariables(string(src)) {
			m.Warnings = append(m.Warnings, fmt.Sprintf("%s: the post-backup function reads $%s, which the pre-backup function sets. The hooks now run as separate processes, so pass it through a file in $ARCHIVER_STATE_DIR instead.", dir, v))
		}
	}
	return m, nil
}

// created lists the hook files this migration writes, filters included, for filter lines
// that named the settings file: they must keep selecting what the hooks now live in.
func (m *Migration) created() []string {
	return append(append([]string{}, m.Wrote...), Filters, LegacyKept)
}

// renameInFilter rewrites a filter line that names the settings file into one line per
// file that replaces it, keeping its prefix (+, -, or a path).
func renameInFilter(line string, files []string) []string {
	if !strings.HasSuffix(line, Legacy) {
		return []string{line}
	}
	prefix := strings.TrimSuffix(line, Legacy)
	seen := map[string]bool{}
	var out []string
	for _, f := range files {
		if !seen[f] {
			seen[f] = true
			out = append(out, prefix+f)
		}
	}
	return out
}

var (
	shellVariable = regexp.MustCompile(`\$(\{|[A-Za-z_])`)
	assignment    = regexp.MustCompile(`(?m)(?:^|[\s;])(?:export\s+|declare\s+(?:-\S+\s+)*)?([A-Za-z_][A-Za-z0-9_]*)=`)
	localDecl     = regexp.MustCompile(`local\s+(?:-\S+\s+)*([A-Za-z_][A-Za-z0-9_]*)`)
)

// sharedVariables finds variables the pre-backup function assigns without local and the
// post-backup function reads. A heuristic: it can only warn.
func sharedVariables(src string) []string {
	pre, post := body(src, "service_specific_pre_backup_function"), body(src, "service_specific_post_backup_function")
	if pre == "" || post == "" {
		return nil
	}
	locals := map[string]bool{}
	for _, m := range localDecl.FindAllStringSubmatch(pre, -1) {
		locals[m[1]] = true
	}
	var out []string
	seen := map[string]bool{}
	for _, m := range assignment.FindAllStringSubmatch(pre, -1) {
		v := m[1]
		if locals[v] || seen[v] {
			continue
		}
		if regexp.MustCompile(`\$\{?` + v + `\b`).MatchString(post) {
			seen[v] = true
			out = append(out, v)
		}
	}
	return out
}

// body is a function's text between its braces, matched by depth.
func body(src, name string) string {
	loc := regexp.MustCompile(`(?m)^\s*(?:function\s+)?` + name + `\s*(?:\(\s*\))?\s*\{`).FindStringIndex(src)
	if loc == nil {
		return ""
	}
	depth := 1
	for i := loc[1]; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return src[loc[1]:i]
			}
		}
	}
	return src[loc[1]:]
}

// arrayText is the source of the DUPLICACY_FILTERS_PATTERNS assignment, roughly.
func arrayText(src string) string {
	i := strings.Index(src, "DUPLICACY_FILTERS_PATTERNS=")
	if i < 0 {
		return ""
	}
	rest := src[i:]
	if j := strings.Index(rest, ")"); j >= 0 {
		return rest[:j]
	}
	return rest
}
